// Generate BOARD.md, ROADMAP.md, BRAGLOG.md and portfolio.html from
// portfolio item frontmatter.
//
// Usage: node build-views.mts [--root DIR]     (Node >= 22.18)
// Warnings go to stderr; exit code is 0 unless the portfolio directory
// itself is missing. node: stdlib only — port of build_views.py.

import { readFileSync, writeFileSync, readdirSync, existsSync, realpathSync } from "node:fs";
import { join, resolve } from "node:path";
import process from "node:process";

export const DONE_STATES = new Set(["done", "dropped", "promoted"]);
export const GENERATED = "<!-- GENERATED by build-views.mts — do not edit by hand -->";

export interface Item {
  id: string; type: string; title: string; status: string; horizon: string;
  blockedBy: string[]; brief: string; artifact: string; epic: string;
  summary: string; file: string; updated: string; completed: string;
  created: string; story: string;
}
export type Items = Map<string, Item>;

export function parseFrontmatter(text: string): [Record<string, string>, string] {
  const lines = text.split(/\r?\n/);
  if (lines.length === 0 || lines[0].trim() !== "---") return [{}, text];
  const fm: Record<string, string> = {};
  let i = 1;
  while (i < lines.length && lines[i].trim() !== "---") {
    const line = lines[i];
    i += 1;
    if (!line.trim() || line.trimStart().startsWith("#")) continue;
    const m = /^([A-Za-z][A-Za-z-]*):\s*(.*)$/.exec(line);
    if (m) {
      let value = m[2].trim();
      if (value.length >= 2 && value[0] === value[value.length - 1] && "\"'".includes(value[0])) {
        value = value.slice(1, -1);
      }
      fm[m[1]] = value;
    }
  }
  return [fm, lines.slice(i + 1).join("\n")];
}

export function parseIdList(value: string): string[] {
  let v = value.trim();
  if (v.startsWith("[") && v.endsWith("]")) v = v.slice(1, -1);
  return v.split(",").map((s) => s.trim()).filter(Boolean);
}

export function firstBodyLine(body: string): string {
  const lines = body.split(/\r?\n/);
  let start = -1;
  for (let i = 0; i < lines.length; i++) {
    const s = lines[i].trim();
    if (s && !s.startsWith("#") && !s.startsWith("<!--")) { start = i; break; }
  }
  if (start < 0) return "";
  const parts = [lines[start].trim()];
  for (const line of lines.slice(start + 1)) {
    const s = line.trim();
    if (!s || s.startsWith("#")) break;
    parts.push(s);
  }
  return parts.join(" ");
}
