#!/usr/bin/env python3
"""Generate BOARD.md and ROADMAP.md from portfolio item frontmatter.

Usage: python3 build_views.py [--root DIR]
Warnings go to stderr; exit code is always 0 unless the portfolio
directory itself is missing. Python 3 stdlib only — rewritten from
build-board.sh because dependency graphs (blocked-by, cycles) are
impractical in shell.
"""
import argparse
import datetime
import html as html_mod
import re
import sys
from pathlib import Path

DONE_STATES = {"done", "dropped", "promoted"}
GENERATED = "<!-- GENERATED by build-views.sh — do not edit by hand -->"


def portfolio_name(root):
    """Optional display name for the HTML view, from a .title file."""
    p = root / ".title"
    if p.is_file():
        return p.read_text(encoding="utf-8").strip()
    return ""


def parse_frontmatter(text):
    """Return (frontmatter dict, body str). Tolerates missing frontmatter."""
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        return {}, text
    fm = {}
    i = 1
    while i < len(lines) and lines[i].strip() != "---":
        line = lines[i]
        i += 1
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        m = re.match(r"^([A-Za-z][A-Za-z-]*):\s*(.*)$", line)
        if m:
            value = m.group(2).strip()
            if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
                value = value[1:-1]
            fm[m.group(1)] = value
    return fm, "\n".join(lines[i + 1:])


def parse_id_list(value):
    value = value.strip()
    if value.startswith("[") and value.endswith("]"):
        value = value[1:-1]
    return [v.strip() for v in value.split(",") if v.strip()]


def first_body_line(body):
    """Return the first paragraph of the body as a single space-joined line.

    Skips leading headings/comments, then collects lines starting at the
    first text line and joins them (space-separated) until a blank line or
    a heading ends the paragraph.
    """
    lines = body.splitlines()
    start = None
    for idx, line in enumerate(lines):
        s = line.strip()
        if s and not s.startswith("#") and not s.startswith("<!--"):
            start = idx
            break
    if start is None:
        return ""
    parts = [lines[start].strip()]
    for line in lines[start + 1:]:
        s = line.strip()
        if not s or s.startswith("#"):
            break
        parts.append(s)
    return " ".join(parts)


def load_items(root):
    items, warnings = {}, []

    def add(path):
        fm, body = parse_frontmatter(path.read_text(encoding="utf-8"))
        if not fm:
            # No frontmatter at all — a plain reference doc (e.g. a story's
            # `brief`), not a portfolio item. Skip silently.
            return
        iid = fm.get("id")
        if not iid:
            warnings.append(f"{path}: missing id")
            return
        if iid in items:
            warnings.append(f"{path}: duplicate id {iid} (also in {items[iid]['file']})")
            return
        items[iid] = {
            "id": iid,
            "type": fm.get("type", ""),
            "title": fm.get("title", ""),
            "status": fm.get("status", ""),
            "horizon": fm.get("horizon", ""),
            "blocked_by": parse_id_list(fm.get("blocked-by", "")),
            "brief": fm.get("brief", ""),
            "artifact": fm.get("artifact", ""),
            "epic": fm.get("epic", ""),
            "summary": first_body_line(body),
            "file": str(path),
            "updated": fm.get("updated", ""),
            "completed": fm.get("completed", ""),
            "created": fm.get("created", ""),
            "story": fm.get("story", ""),
        }

    for path in sorted((root / "epics").glob("*/*.md")):
        add(path)
    inbox = root / "inbox"
    if inbox.is_dir():
        for path in sorted(inbox.glob("*.md")):
            add(path)
    return items, warnings


def validate(items):
    warnings = []
    for it in sorted(items.values(), key=lambda x: x["id"]):
        for dep in it["blocked_by"]:
            if dep not in items:
                warnings.append(f"{it['id']}: unknown blocked-by id {dep}")
        valid = {"future", "active", "blocked", "done", "dropped", "parked",
                 "promoted"}
        if it["status"] and it["status"] not in valid:
            warnings.append(f"{it['id']}: unknown status '{it['status']}'")
        if it["type"] == "idea" and it["horizon"] not in ("", "later", "next"):
            warnings.append(
                f"{it['id']}: idea horizon '{it['horizon']}' not supported "
                "(use later or next; promote the idea instead)")
    state = {}  # id -> 1 visiting, 2 done

    def visit(iid, stack):
        state[iid] = 1
        for dep in items[iid]["blocked_by"]:
            if dep not in items:
                continue
            if state.get(dep) == 1:
                warnings.append("dependency cycle: " + " -> ".join(stack + [dep]))
            elif dep not in state:
                visit(dep, stack + [dep])
        state[iid] = 2

    for iid in sorted(items):
        if iid not in state:
            visit(iid, [iid])
    return warnings


def pending_blockers(item, items):
    return [d for d in item["blocked_by"]
            if d in items and items[d]["status"] not in DONE_STATES]


def item_epic(item, items):
    """Parent epic dict for a story/task, or None."""
    eid = item.get("epic")
    return items.get(eid) if eid else None


def is_parked(item, items):
    """True if the item is parked, or its parent epic is parked (cascade)."""
    if item["status"] == "parked":
        return True
    e = item_epic(item, items)
    return bool(e and e["status"] == "parked")


def ship_date(item):
    """The date an item shipped: `completed` if set, else `updated`."""
    return item.get("completed") or item.get("updated") or ""


def within_days(date_str, today_str, days):
    """True if date_str is a valid ISO date within `days` before today_str."""
    try:
        d = datetime.date.fromisoformat(date_str)
        t = datetime.date.fromisoformat(today_str)
    except ValueError:
        return False
    return 0 <= (t - d).days <= days


def epic_horizon(item):
    if item["horizon"]:
        return item["horizon"]
    return "now" if item["status"] == "active" else "later"


def marks(item):
    m = ""
    if item["brief"]:
        m += " 📄"
    if item["artifact"]:
        m += " 🔗"
    return m


def blocked_suffix(item, items):
    pend = pending_blockers(item, items)
    return " ⛔ after " + ", ".join(pend) if pend else ""


def ships_after_line(item, items):
    pend = pending_blockers(item, items)
    if not pend:
        return ""
    parts = [f"{d} ({items[d]['title']})" for d in pend]
    return "  - _ships after: " + ", ".join(parts) + "_"


def stories_of(epic_id, items):
    return sorted((x for x in items.values()
                   if x["type"] == "story" and x["epic"] == epic_id),
                  key=lambda x: x["id"])


def epics(items):
    return sorted((x for x in items.values() if x["type"] == "epic"),
                  key=lambda x: x["id"])


def board_lane(item, items):
    """Which kanban lane a story/task card belongs in, or None if off-board."""
    if is_parked(item, items) or item["status"] in ("dropped", "done"):
        return None
    if item["status"] == "blocked" or pending_blockers(item, items):
        return "blocked"
    if item["status"] == "active":
        return "active"
    if item["status"] == "future":
        return "ready"
    return None


BOARD_LANES = [("blocked", "⛔ Blocked"), ("ready", "🎬 Ready for Dev"),
               ("active", "🏃 Active")]
# The per-epic board pane shows these three status columns (no Shipped —
# done work lives in the Braglog).
EPIC_LANES = [("ready", "Ready for Dev"), ("active", "Active"),
              ("blocked", "Blocked")]


def render_board(items, today):
    out = [GENERATED, "# Portfolio Board", "", f"_Last generated: {today}_", ""]
    cards = sorted((x for x in items.values() if x["type"] in ("story", "task")),
                   key=lambda x: x["id"])
    for lane, heading in BOARD_LANES:
        out += [f"## {heading}", ""]
        rows = [c for c in cards if board_lane(c, items) == lane]
        for c in rows:
            epic = item_epic(c, items)
            tag = f" — {epic['id']} {epic['title']}" if epic else ""
            out.append(f"- [{c['id']}] {c['title']}{tag}"
                       f"{marks(c)}{blocked_suffix(c, items)}")
        if not rows:
            out.append("_(none)_")
        out.append("")
    out += ["## 🏆 Shipped (last 30 days)", ""]
    shipped = [e for e in epics(items) if e["status"] == "done"
               and within_days(ship_date(e), today, 30)]
    shipped.sort(key=lambda e: ship_date(e), reverse=True)
    for e in shipped:
        out.append(f"- [{e['id']}] {e['title']} — {ship_date(e)}{marks(e)}")
    if not shipped:
        out.append("_(none)_")
    out.append("")
    return "\n".join(out) + "\n"


def _roadmap_epic_md(e, items, with_summary=False):
    """An epic as a <details> accordion listing its non-done stories."""
    open_stories = [s for s in stories_of(e["id"], items)
                    if s["status"] not in DONE_STATES]
    count = f"{len(open_stories)} stor{'y' if len(open_stories) == 1 else 'ies'}"
    lines = ["<details>",
             f"<summary>[{e['id']}] {e['title']}{marks(e)} — {count}"
             f"{blocked_suffix(e, items)}</summary>", ""]
    if with_summary and e["summary"]:
        lines.append(e["summary"])
    for s in open_stories:
        lines.append(f"- [{s['id']}] {s['title']} — `{s['status']}`"
                     f"{marks(s)}{blocked_suffix(s, items)}")
        after = ships_after_line(s, items)
        if after:
            lines.append(after)
    lines += ["</details>", ""]
    return lines


def render_roadmap(items, today):
    out = [GENERATED, "# Roadmap", "", f"_Last generated: {today}_", ""]
    future = [e for e in epics(items) if e["status"] == "future"]
    parked = [e for e in epics(items) if e["status"] == "parked"]
    ideas = sorted((x for x in items.values()
                    if x["type"] == "idea" and x["status"] == "future"),
                   key=lambda x: x["id"])
    next_ideas = [i for i in ideas if i["horizon"] == "next"]
    later_ideas = [i for i in ideas if i["horizon"] != "next"]

    out += ["## ⏭️ Next", ""]
    next_epics = [e for e in future if epic_horizon(e) == "next"]
    for e in next_epics:
        out += _roadmap_epic_md(e, items, with_summary=True)
    for i in next_ideas:
        summary = f" — {i['summary']}" if i["summary"] else ""
        out.append(f"- [{i['id']}] {i['title']} 💡{summary}")
    if not next_epics and not next_ideas:
        out.append("_(none)_")
    out.append("")

    out += ["## 🌅 Later", ""]
    later_epics = [e for e in future if epic_horizon(e) != "next"]
    for e in later_epics:
        out += _roadmap_epic_md(e, items)
    for i in later_ideas:
        summary = f" — {i['summary']}" if i["summary"] else ""
        out.append(f"- [{i['id']}] {i['title']} 💡{summary}")
    if not later_epics and not later_ideas:
        out.append("_(none)_")
    out.append("")

    out += ["## ⏸️ Parked", ""]
    for e in parked:
        out += _roadmap_epic_md(e, items, with_summary=True)
    if not parked:
        out.append("_(none)_")
    out.append("")
    return "\n".join(out) + "\n"


def month_label(date_str):
    try:
        d = datetime.date.fromisoformat(date_str)
    except ValueError:
        return "Undated"
    return d.strftime("%B %Y")


def render_braglog(items, today):
    out = [GENERATED, "# Braglog", "", f"_Last generated: {today}_", "",
           "_What's shipped, newest first._", ""]
    done = [x for x in items.values()
            if x["status"] == "done" and x["type"] in ("epic", "story")]
    done.sort(key=lambda x: (ship_date(x), x["id"]), reverse=True)
    current = None
    for x in done:
        label = month_label(ship_date(x))
        if label != current:
            current = label
            out += ["", f"## {label}", ""]
        epic = item_epic(x, items)
        tag = f" — {epic['id']} {epic['title']}" if epic else ""
        kind = "🏆" if x["type"] == "epic" else "•"
        out.append(f"- {ship_date(x)} {kind} [{x['id']}] {x['title']}{tag}")
    if not done:
        out.append("_(nothing shipped yet)_")
    out.append("")
    return "\n".join(out) + "\n"


# ---------------------------------------------------------------- HTML view

HTML_CSS = """
:root{
  --court:#14110D;--floor:#1E1913;--floor2:#241E16;--line:#31291F;
  --chalk:#EFE7DA;--dust:#A69B8C;--faint:#928873;
  --orange:#FF6A1A;--orange-dim:#B34A12;
  --st-future:#8FA8C4;--st-active:#64B98C;--st-blocked:#E05C4B;--st-done:#9C9284;
  /* Low-chroma per-epic "taped-floor" tints — group without competing with orange */
  --e-0:#C98A3C;--e-1:#6E96B0;--e-2:#8CA67A;--e-3:#B07C86;--e-4:#9A8CB5;--e-5:#C0A15A;
  --mono:ui-monospace,'Cascadia Code','SF Mono',Menlo,Consolas,monospace;
  --disp:'Archivo Narrow','Arial Narrow','Roboto Condensed',system-ui,sans-serif;
}
*{box-sizing:border-box}
body{background:var(--court);color:var(--chalk);margin:0;line-height:1.5;
  font-family:system-ui,'Segoe UI',Roboto,'Helvetica Neue',sans-serif}
.wrap{max-width:940px;margin:0 auto;padding:0 24px 80px}
a{color:var(--orange);text-decoration:none}
a:hover,a:focus-visible{text-decoration:underline}
:focus-visible{outline:2px solid var(--orange);outline-offset:2px}
header{padding:48px 0 28px;border-bottom:3px solid var(--orange);
  display:flex;flex-wrap:wrap;align-items:flex-end;justify-content:space-between;gap:16px}
.eyebrow{font-family:var(--mono);font-size:12px;letter-spacing:.22em;
  color:var(--orange);text-transform:uppercase}
h1{font-family:var(--disp);font-weight:900;text-transform:uppercase;
  font-size:clamp(34px,6vw,52px);line-height:.95;margin:10px 0 0}
.stamp{font-family:var(--mono);font-size:12px;color:var(--faint);text-align:right}
.boxscore{display:flex;flex-wrap:wrap;margin:26px 0 0;border:1px solid var(--line);background:var(--floor)}
.bs{flex:1 1 110px;padding:12px 16px;border-right:1px solid var(--line)}
.bs:last-child{border-right:0}
.bs b{font-family:var(--mono);font-variant-numeric:tabular-nums;font-size:24px;
  font-weight:700;display:block;color:var(--chalk)}
.bs b.o{color:var(--orange)}
.bs span{font-family:var(--mono);font-size:11px;letter-spacing:.16em;
  text-transform:uppercase;color:var(--dust)}
h2{font-family:var(--disp);font-weight:900;text-transform:uppercase;
  font-size:clamp(22px,3vw,28px);margin:56px 0 18px;display:flex;align-items:baseline;gap:12px}
h2::before{content:'';width:24px;height:11px;background:var(--orange);flex:none}
h3.group{font-family:var(--mono);font-size:12px;letter-spacing:.2em;text-transform:uppercase;
  color:var(--dust);margin:28px 0 10px;border-bottom:1px solid var(--line);padding-bottom:6px}
.epic{background:var(--floor);border:1px solid var(--line);margin-bottom:14px}
.epic-head{display:flex;flex-wrap:wrap;align-items:center;gap:10px;
  padding:12px 16px;border-bottom:1px solid var(--line);background:var(--floor2)}
.epic-head .t{font-family:var(--disp);font-weight:700;text-transform:uppercase;
  letter-spacing:.04em;font-size:16px}
.epic-sum{padding:10px 16px 0;color:var(--dust);font-size:13.5px;max-width:75ch}
.rows{list-style:none;margin:0;padding:8px 8px}
.rows li{display:flex;flex-wrap:wrap;align-items:baseline;gap:8px;padding:6px 8px;font-size:14px}
.rows li+li{border-top:1px solid #241E1655}
.rows .t{color:var(--chalk)}
.rows .ships{flex-basis:100%;font-size:12px;color:var(--faint);padding-left:46px}
.flat{list-style:none;margin:0;padding:0}
.flat li{display:flex;flex-wrap:wrap;align-items:baseline;gap:8px;
  background:var(--floor);border:1px solid var(--line);padding:10px 14px;margin-bottom:8px;font-size:14px}
.flat .sum{color:var(--faint);font-size:12.5px;flex-basis:100%;padding-left:46px}
.chip{font-family:var(--mono);font-weight:700;font-size:11.5px;padding:1px 7px;
  border-radius:3px;background:#000;border:1px solid var(--line);letter-spacing:.05em;white-space:nowrap}
.chip.e{color:var(--orange);border-color:var(--orange-dim)}
.chip.s{color:var(--st-future);border-color:#3c4c5e;background:#141b22}
.chip.t{color:var(--chalk);border-color:var(--faint);background:var(--floor2)}
.chip.i{color:#D9B36A;border-color:#5e4c2c}
.pill{font-family:var(--mono);font-size:11px;letter-spacing:.08em;text-transform:uppercase;
  padding:1px 8px;border-radius:20px;border:1px solid;white-space:nowrap}
.pill.future{color:var(--st-future);border-color:var(--st-future)}
.pill.active{color:var(--st-active);border-color:var(--st-active)}
.pill.blocked{color:var(--st-blocked);border-color:var(--st-blocked)}
.pill.done,.pill.dropped{color:var(--st-done);border-color:var(--st-done)}
.blk{font-family:var(--mono);font-size:11.5px;color:var(--st-blocked);white-space:nowrap}
.mark{font-size:13px}
.none{color:var(--dust);font-size:14px;font-style:italic}
footer{margin-top:64px;border-top:1px solid var(--line);padding-top:16px;
  font-family:var(--mono);font-size:11.5px;color:var(--faint)}
@media (max-width:560px){.rows .ships,.flat .sum{padding-left:0}}
.tabs{display:flex;gap:4px;margin:26px 0 0;border-bottom:1px solid var(--line)}
.tabs a{font-family:var(--disp);font-weight:700;text-transform:uppercase;
  letter-spacing:.06em;font-size:14px;color:var(--dust);padding:10px 16px;
  border:1px solid transparent;border-bottom:none;border-radius:4px 4px 0 0}
.tabs a.active{color:var(--court);background:var(--orange);border-color:var(--orange)}
.tab{padding-top:8px}
.tab[hidden]{display:none}
.lanes{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-top:18px}
.lane{background:var(--floor);border:1px solid var(--line);min-width:0}
.lane h3{font-family:var(--mono);font-size:12px;letter-spacing:.14em;
  text-transform:uppercase;color:var(--chalk);margin:0;padding:10px 12px;
  border-bottom:1px solid var(--line);background:var(--floor2)}
.lane ul{list-style:none;margin:0;padding:8px}
.card{position:relative;background:var(--floor);border:1px solid var(--line);
  border-left:3px solid var(--ea,var(--line));border-radius:5px;
  padding:10px 12px 10px 13px;margin-bottom:10px}
.card.blocked{border-left-color:var(--st-blocked)}
.card .t{display:block;font-family:var(--disp);font-weight:700;font-size:15px;
  line-height:1.25;letter-spacing:.01em;color:var(--chalk);margin:0 0 6px}
.card .meta{display:flex;flex-wrap:wrap;align-items:center;gap:6px}
.card .ep-tag{font-family:var(--mono);font-size:11px;font-weight:700;
  padding:1px 6px;border-radius:3px;color:var(--ea,var(--dust));
  border:1px solid var(--ea,var(--line));opacity:.9;background:transparent}
.card .blk{display:inline-flex;align-items:center;gap:4px;margin-top:6px}
.card .tick{display:block;width:22px;height:2px;background:var(--orange);margin-top:6px}
.card.shipped{border-color:var(--orange-dim)}
.card.shipped .d{font-family:var(--mono);font-size:12px;color:var(--dust)}
@media (prefers-reduced-motion:no-preference){
  .card{transition:border-color .12s ease}
}
.card:hover{border-color:var(--dust)}
.board-wrap{display:flex;gap:18px;align-items:flex-start;margin-top:18px}
.rail{flex:0 0 214px;border:1px solid var(--line);background:var(--floor);
  border-radius:6px;overflow:hidden}
.rail a{display:flex;align-items:center;gap:9px;padding:10px 12px;color:var(--chalk);
  font-size:13px;border-left:3px solid transparent}
.rail a+a{border-top:1px solid var(--line)}
.rail .dot{width:9px;height:9px;border-radius:50%;background:var(--ea,var(--dust));flex:none}
.rail .rl{flex:1;min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
.rail .rl .chip{margin-right:5px}
.rail .n{font-family:var(--mono);font-size:11px;color:var(--dust);
  font-variant-numeric:tabular-nums}
.rail a.active{background:var(--floor2);border-left-color:var(--ea,var(--orange));font-weight:600}
.rail a:hover{background:var(--floor2)}
.panes{flex:1;min-width:0}
.pane-head{display:flex;align-items:center;gap:10px;margin:0 0 6px;padding-bottom:8px;
  font-family:var(--disp);font-weight:800;text-transform:uppercase;font-size:18px;
  letter-spacing:.02em;border-bottom:2px solid var(--ea,var(--orange))}
.epic-pane .epic-sum{margin:6px 0 14px;padding:0;color:var(--dust);font-size:13.5px;max-width:70ch}
.lanes3{grid-template-columns:repeat(3,1fr)}
.pane-foot{margin-top:14px;font-family:var(--mono);font-size:12px;color:var(--dust)}
@media (max-width:720px){.board-wrap{flex-direction:column}
  .rail{flex:none;width:100%}.lanes3{grid-template-columns:1fr}}
details.epic-acc{background:var(--floor);border:1px solid var(--line);margin-bottom:10px}
details.epic-acc summary{cursor:pointer;padding:12px 16px;font-family:var(--disp);
  font-weight:700;text-transform:uppercase;letter-spacing:.04em;font-size:15px;
  list-style:none;display:flex;flex-wrap:wrap;align-items:center;gap:10px}
details.epic-acc summary::-webkit-details-marker{display:none}
details.epic-acc[open] summary{border-bottom:1px solid var(--line);background:var(--floor2)}
.count{font-family:var(--mono);font-size:12px;color:var(--dust);font-weight:400}
.brag h3{display:flex;align-items:baseline;gap:10px;font-family:var(--disp);
  font-weight:900;text-transform:uppercase;font-size:20px;margin:34px 0 12px;color:var(--orange)}
.brag ul{list-style:none;position:relative;margin:0 0 8px 8px;padding:0;
  border-left:2px solid var(--line)}
.brag li{position:relative;display:grid;grid-template-columns:92px 1fr;
  align-items:baseline;gap:14px;padding:9px 0 9px 22px;border-bottom:1px solid #241E1655}
.brag li::before{content:'';position:absolute;left:-6px;top:15px;width:9px;height:9px;
  border-radius:50%;background:var(--ea,var(--dust));border:2px solid var(--court)}
.brag .d{font-family:var(--mono);font-size:12px;color:var(--dust);
  font-variant-numeric:tabular-nums}
.brag .c{min-width:0}
.brag .t{font-size:14px;color:var(--chalk)}
.brag .ep-name{font-family:var(--mono);font-size:11px;margin-left:8px;
  color:var(--ea,var(--dust));opacity:.9;white-space:nowrap}
.brag .tick{display:inline-block;width:22px;height:2px;background:var(--orange);
  vertical-align:middle;margin-left:8px}
.brag li.epic-done{padding:14px 0 14px 22px;border-bottom:1px solid var(--line)}
.brag li.epic-done .t{font-family:var(--disp);font-weight:900;text-transform:uppercase;
  font-size:16px;letter-spacing:.03em}
.brag li.epic-done::before{width:13px;height:13px;left:-8px;top:17px;
  background:var(--orange);box-shadow:0 0 0 3px rgba(255,106,26,.18)}
@media (max-width:820px){.lanes{grid-template-columns:1fr;}}
@media (max-width:560px){.brag li{grid-template-columns:1fr;gap:2px}}
"""


def _h(text):
    return html_mod.escape(text, quote=True)


def _chip(iid):
    cls = {"E": "e", "S": "s", "T": "t", "I": "i"}.get(iid[:1], "t")
    return f'<span class="chip {cls}">{_h(iid)}</span>'


def _pill(status):
    return f'<span class="pill {_h(status)}">{_h(status)}</span>' if status else ""


def _marks_html(item):
    out = ""
    if item["brief"]:
        href = item["brief"]
        if href.startswith("portfolio/"):
            href = href[len("portfolio/"):]
        out += f' <a class="mark" href="{_h(href)}" title="brief">📄</a>'
    if item["artifact"]:
        out += f' <a class="mark" href="{_h(item["artifact"])}" title="artifact">🔗</a>'
    return out


def _blocked_html(item, items):
    pend = pending_blockers(item, items)
    if not pend:
        return ""
    return f'<span class="blk">⛔ after {_h(", ".join(pend))}</span>'


def _ships_html(item, items):
    pend = pending_blockers(item, items)
    if not pend:
        return ""
    parts = ", ".join(f"{d} ({items[d]['title']})" for d in pend)
    return f'<div class="ships">ships after: {_h(parts)}</div>'


def _story_row(s, items):
    return (f'<li>{_chip(s["id"])} <span class="t">{_h(s["title"])}</span> '
            f'{_pill(s["status"])}{_marks_html(s)} {_blocked_html(s, items)}'
            f'{_ships_html(s, items)}</li>')


def _flat_row(item, with_summary=True):
    summary = (f'<div class="sum">{_h(item["summary"])}</div>'
               if with_summary and item["summary"] else "")
    idea = " 💡" if item["type"] == "idea" else ""
    return (f'<li>{_chip(item["id"])} <span class="t">{_h(item["title"])}</span>'
            f'{idea}{_marks_html(item)}{summary}</li>')


def _epic_accent(epic_id):
    """A stable low-chroma tint var for an epic id, for spines and nodes."""
    try:
        n = int(epic_id[1:]) % 6
    except (ValueError, IndexError):
        n = 0
    return f"var(--e-{n})"


def _board_card(c, items, show_epic=True):
    """A story/task card: title is the hero; epic reduced to a tinted chip.

    No status pill — the column already encodes status. The left spine is the
    epic's tint (red when blocked); the full epic name lives in a tooltip.
    `show_epic=False` drops the epic chip (used inside a per-epic pane, where
    every card already belongs to the pane's epic).
    """
    epic = item_epic(c, items)
    ea = _epic_accent(epic["id"]) if epic else "var(--line)"
    ep = (f'<span class="ep-tag" title="{_h(epic["title"])}">{_h(epic["id"])}</span>'
          if epic and show_epic else "")
    blocked_cls = " blocked" if (c["status"] == "blocked"
                                 or pending_blockers(c, items)) else ""
    return (f'<li><div class="card{blocked_cls}" style="--ea:{ea}">'
            f'<span class="t">{_h(c["title"])}</span>'
            f'<span class="meta">{_chip(c["id"])}{ep}{_marks_html(c)}</span>'
            f'{_blocked_html(c, items)}</div></li>')


def _epic_pane(e, items, cards):
    """A single epic's board pane: header + Ready/Active/Blocked columns.

    Hidden by default; the rail nav reveals the selected pane. Cards omit the
    epic chip (the whole pane is the epic). Done work is a footer count only.
    """
    ea = _epic_accent(e["id"])
    mine = [c for c in cards if c["epic"] == e["id"]]
    lanes = []
    for lane, label in EPIC_LANES:
        rows = "".join(_board_card(c, items, show_epic=False)
                       for c in mine if board_lane(c, items) == lane)
        body = f'<ul>{rows}</ul>' if rows else '<p class="none">(none)</p>'
        lanes.append(f'<div class="lane"><h3>{label}</h3>{body}</div>')
    shipped_n = sum(1 for c in mine if c["status"] == "done")
    summ = (f'<p class="epic-sum">{_h(e["summary"])}</p>' if e["summary"] else "")
    foot = (f'<p class="pane-foot">{shipped_n} shipped → Braglog</p>'
            if shipped_n else "")
    return (f'<div class="epic-pane" data-epic="{_h(e["id"])}" hidden '
            f'style="--ea:{ea}"><div class="pane-head">{_chip(e["id"])}'
            f'<span class="pt">{_h(e["title"])}</span></div>{summ}'
            f'<div class="lanes lanes3">{"".join(lanes)}</div>{foot}</div>')


def _shipped_card(e, hot=False):
    """A shipped epic card. `hot` marks the single freshest ship (score-tick)."""
    ea = _epic_accent(e["id"])
    tick = '<span class="tick"></span>' if hot else ""
    return (f'<li><div class="card shipped" style="--ea:{ea}">'
            f'<span class="t">{_h(e["title"])}</span>{tick}'
            f'<span class="meta">{_chip(e["id"])}'
            f'<span class="d">{_h(ship_date(e))}</span></span></div></li>')


def _roadmap_acc(e, items, with_summary=False):
    open_stories = [s for s in stories_of(e["id"], items)
                    if s["status"] not in DONE_STATES]
    count = f"{len(open_stories)} stor{'y' if len(open_stories) == 1 else 'ies'}"
    rows = "".join(_story_row(s, items) for s in open_stories)
    body = f'<ul class="rows">{rows}</ul>' if rows else ""
    summary = (f'<p class="epic-sum">{_h(e["summary"])}</p>'
               if with_summary and e["summary"] else "")
    return (f'<details class="epic-acc"><summary>{_chip(e["id"])}'
            f'<span>{_h(e["title"])}</span>{_marks_html(e)}'
            f'<span class="count">{count}</span>{_blocked_html(e, items)}'
            f'</summary>{summary}{body}</details>')


def render_html(items, today, name=""):
    future = [e for e in epics(items) if e["status"] == "future"]
    parked = [e for e in epics(items) if e["status"] == "parked"]
    ideas = sorted((x for x in items.values()
                    if x["type"] == "idea" and x["status"] == "future"),
                   key=lambda x: x["id"])
    next_ideas = [i for i in ideas if i["horizon"] == "next"]
    later_ideas = [i for i in ideas if i["horizon"] != "next"]
    n_stories = sum(1 for x in items.values() if x["type"] == "story")
    n_tasks = sum(1 for x in items.values() if x["type"] == "task")
    n_active = sum(1 for x in items.values()
                   if x["type"] == "epic" and x["status"] == "active")
    n_shipped = sum(1 for x in items.values()
                    if x["type"] == "epic" and x["status"] == "done")

    cards = sorted((x for x in items.values() if x["type"] in ("story", "task")),
                   key=lambda x: x["id"])

    out = []
    eyebrow = f"{_h(name)} · work tracking · generated" if name \
        else "work tracking · generated"
    out.append(f'<header><div><div class="eyebrow">{eyebrow}</div>'
               '<h1>Portfolio</h1></div>'
               f'<div class="stamp">build-views.sh<br>{_h(today)}</div></header>')
    out.append('<div class="boxscore">'
                f'<div class="bs"><b class="o">{n_active}</b><span>Epics active</span></div>'
                f'<div class="bs"><b>{n_stories}</b><span>Stories</span></div>'
                f'<div class="bs"><b>{n_tasks}</b><span>Tasks</span></div>'
                f'<div class="bs"><b>{len(ideas)}</b><span>Ideas</span></div>'
                f'<div class="bs"><b class="o">{n_shipped}</b><span>Epics shipped</span></div>'
                '</div>')

    # Tab bar
    out.append('<nav class="tabs" role="tablist" aria-label="Portfolio views">'
               '<a href="#board" data-tab="board" id="tab-board" role="tab" '
               'aria-controls="board" aria-selected="true">Board</a>'
               '<a href="#roadmap" data-tab="roadmap" id="tab-roadmap" role="tab" '
               'aria-controls="roadmap" aria-selected="false">Roadmap</a>'
               '<a href="#braglog" data-tab="braglog" id="tab-braglog" role="tab" '
               'aria-controls="braglog" aria-selected="false">Braglog</a></nav>')

    # Board — a left epic rail + panes. The "All work" pane is the cross-epic
    # status board; each other pane is one epic's Ready/Active/Blocked columns.
    def _open_count(eid):
        return sum(1 for c in cards
                   if c["epic"] == eid and board_lane(c, items) is not None)

    # Only epics with open work appear in the rail — an epic whose stories are
    # all shipped/parked is "finished" and drops out of the board navigation
    # (it still lives in the Braglog / Roadmap).
    board_epics = sorted(
        (e for e in epics(items)
         if e["status"] in ("active", "future") and _open_count(e["id"]) > 0),
        key=lambda e: (0 if e["status"] == "active" else 1, e["id"]))

    all_lanes = []
    for lane, heading in BOARD_LANES:
        rows = "".join(_board_card(c, items) for c in cards
                       if board_lane(c, items) == lane)
        body = f'<ul>{rows}</ul>' if rows else '<p class="none">(none)</p>'
        all_lanes.append(f'<div class="lane"><h3>{heading}</h3>{body}</div>')
    shipped = [e for e in epics(items) if e["status"] == "done"
               and within_days(ship_date(e), today, 30)]
    shipped.sort(key=lambda e: ship_date(e), reverse=True)
    srows = "".join(_shipped_card(e, hot=(i == 0)) for i, e in enumerate(shipped))
    sbody = f'<ul>{srows}</ul>' if shipped else '<p class="none">(none)</p>'
    all_lanes.append(f'<div class="lane"><h3>🏆 Shipped · 30d</h3>{sbody}</div>')

    rail = ['<nav class="rail" aria-label="Epics">',
            '<a href="#board" data-epic-nav="all" class="active" '
            'style="--ea:var(--orange)"><span class="dot"></span>'
            '<span class="rl">All work</span></a>']
    for e in board_epics:
        rail.append(
            f'<a href="#board/{_h(e["id"])}" data-epic-nav="{_h(e["id"])}" '
            f'style="--ea:{_epic_accent(e["id"])}"><span class="dot"></span>'
            f'<span class="rl">{_chip(e["id"])}{_h(e["title"])}</span>'
            f'<span class="n">{_open_count(e["id"])}</span></a>')
    rail.append('</nav>')

    panes = [f'<div class="epic-pane" data-epic="all"><div class="lanes">'
             f'{"".join(all_lanes)}</div></div>']
    panes += [_epic_pane(e, items, cards) for e in board_epics]

    out.append(f'<section class="tab" id="board" role="tabpanel" '
               f'aria-labelledby="tab-board"><div class="board-wrap">'
               f'{"".join(rail)}<div class="panes">{"".join(panes)}</div>'
               f'</div></section>')

    # Roadmap
    r = ['<section class="tab" id="roadmap" role="tabpanel" '
         'aria-labelledby="tab-roadmap" hidden>']
    r.append('<h3 class="group">⏭️ Next</h3>')
    next_epics = [e for e in future if epic_horizon(e) == "next"]
    r += [_roadmap_acc(e, items, with_summary=True) for e in next_epics]
    if next_ideas:
        r.append('<ul class="flat">' + "".join(_flat_row(i) for i in next_ideas) + '</ul>')
    if not next_epics and not next_ideas:
        r.append('<p class="none">(none)</p>')
    r.append('<h3 class="group">🌅 Later</h3>')
    later_epics = [e for e in future if epic_horizon(e) != "next"]
    r += [_roadmap_acc(e, items) for e in later_epics]
    if later_ideas:
        r.append('<ul class="flat">' + "".join(_flat_row(i) for i in later_ideas) + '</ul>')
    if not later_epics and not later_ideas:
        r.append('<p class="none">(none)</p>')
    r.append('<h3 class="group">⏸️ Parked</h3>')
    r += [_roadmap_acc(e, items, with_summary=True) for e in parked] \
        or ['<p class="none">(none)</p>']
    r.append('</section>')
    out.append("".join(r))

    # Braglog — a chronological timeline; epic name shown only when it changes
    # down the list (kills repetition, keeps chronology). Epic completions are
    # elevated; the single freshest ship gets the orange score-tick.
    b = ['<section class="tab" id="braglog" role="tabpanel" '
         'aria-labelledby="tab-braglog" hidden><div class="brag">']
    done = [x for x in items.values()
            if x["status"] == "done" and x["type"] in ("epic", "story")]
    done.sort(key=lambda x: (ship_date(x), x["id"]), reverse=True)
    month_counts = {}
    for x in done:
        m = month_label(ship_date(x))
        month_counts[m] = month_counts.get(m, 0) + 1
    current = None
    last_eid = None
    open_ul = False
    for i, x in enumerate(done):
        label = month_label(ship_date(x))
        if label != current:
            if open_ul:
                b.append('</ul>')
            current = label
            last_eid = None
            b.append(f'<h3>{_h(label)}<span class="count">'
                     f'{month_counts[label]} shipped</span></h3><ul>')
            open_ul = True
        tick = '<span class="tick"></span>' if i == 0 else ""
        if x["type"] == "epic":
            ea = _epic_accent(x["id"])
            last_eid = None
            b.append(f'<li class="epic-done" style="--ea:{ea}">'
                     f'<span class="d">{_h(ship_date(x))}</span>'
                     f'<div class="c"><span class="t">🏆 {_h(x["title"])}</span>'
                     f'{tick}</div></li>')
        else:
            epic = item_epic(x, items)
            ea = _epic_accent(epic["id"]) if epic else "var(--line)"
            ep = ""
            if epic and epic["id"] != last_eid:
                ep = (f'<span class="ep-name" title="{_h(epic["title"])}">'
                      f'{_h(epic["id"])} {_h(epic["title"])}</span>')
            if epic:
                last_eid = epic["id"]
            b.append(f'<li style="--ea:{ea}">'
                     f'<span class="d">{_h(ship_date(x))}</span>'
                     f'<div class="c"><span class="t">{_h(x["title"])}</span>'
                     f'{tick}{ep}</div></li>')
    if open_ul:
        b.append('</ul>')
    if not done:
        b.append('<p class="none">(nothing shipped yet)</p>')
    b.append('</div></section>')
    out.append("".join(b))

    out.append('<footer>GENERATED by build-views.sh — do not edit. '
               'Source of truth: the item files in epics/ and inbox/.</footer>')

    script = (
        "<script>(function(){var t=['board','roadmap','braglog'];"
        "function all(q){return document.querySelectorAll(q);}"
        "function show(hash){var p=(hash||'board').split('/');var tab=p[0];"
        "if(t.indexOf(tab)<0)tab='board';"
        "t.forEach(function(x){document.getElementById(x).hidden=(x!==tab);"
        "var a=document.querySelector('[data-tab=\"'+x+'\"]');"
        "if(a){a.classList.toggle('active',x===tab);"
        "a.setAttribute('aria-selected',x===tab);}});"
        "if(tab==='board'){var ep=p[1]||'all';var ok=false;"
        "all('[data-epic]').forEach(function(n){var on=n.getAttribute('data-epic')===ep;"
        "n.hidden=!on;if(on)ok=true;});"
        "if(!ok){ep='all';all('[data-epic]').forEach(function(n){"
        "n.hidden=n.getAttribute('data-epic')!=='all';});}"
        "all('[data-epic-nav]').forEach(function(l){"
        "var on=l.getAttribute('data-epic-nav')===ep;l.classList.toggle('active',on);"
        "if(on)l.setAttribute('aria-current','true');else l.removeAttribute('aria-current');"
        "});}}"
        "function h(){show((location.hash||'#board').slice(1));}"
        "window.addEventListener('hashchange',h);h();})();</script>")

    return ('<!doctype html>\n<html lang="en"><head><meta charset="utf-8">'
            '<meta name="viewport" content="width=device-width, initial-scale=1">'
            f'<title>{_h(name) + " " if name else ""}Portfolio</title>'
            f'<style>{HTML_CSS}</style></head>'
            f'<body><div class="wrap">{"".join(out)}</div>{script}</body></html>\n')


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", default=Path(__file__).resolve().parent,
                        type=Path)
    args = parser.parse_args()
    root = args.root
    items, warnings = load_items(root)
    warnings += validate(items)
    today = datetime.date.today().isoformat()
    (root / "BOARD.md").write_text(render_board(items, today), encoding="utf-8")
    (root / "ROADMAP.md").write_text(render_roadmap(items, today), encoding="utf-8")
    (root / "BRAGLOG.md").write_text(render_braglog(items, today), encoding="utf-8")
    (root / "portfolio.html").write_text(
        render_html(items, today, portfolio_name(root)), encoding="utf-8")
    for w in warnings:
        print(f"warning: {w}", file=sys.stderr)
    print(f"Wrote {root / 'BOARD.md'}, {root / 'ROADMAP.md'}, "
          f"{root / 'BRAGLOG.md'} and {root / 'portfolio.html'}")


if __name__ == "__main__":
    main()
